version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    depends_on:
      - redis

  client:
    build:
      context: ./client
    depends_on:
      - server
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
