version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  server:
    build: ./server
    ports:
      - "50051:50051"
    depends_on:
      - redis

  client:
    build: ./client
    depends_on:
      - server
