version: '3.8'

services:
  server:
    build:
      context: ./count_service/server
    container_name: lab-server
    ports:
      - "50051:50051"
    depends_on:
      - redis

  client:
    build:
      context: ./count_service/client
    container_name: lab-client
    depends_on:
      - server

  load_balancer:
    build:
      context: ./load_balancer
    container_name: lab-load-balancer
    ports:
      - "8080:8080"
    depends_on:
      - server

  redis:
    image: redis:alpine
    container_name: lab-redis
    ports:
      - "6379:6379"
