[[endpoints]]
name = "s1"
ip = "192.168.1.10"
port = 50051
weight = 80

[[endpoints]]
name = "s2"
ip = "192.168.1.11"
port = 50051
weight = 10

[[endpoints]]
name = "s3"
ip = "192.168.1.12"
port = 50051
weight = 10