[[endpoints]]
name = "server1"
ip = "192.168.1.10"
port = 50051
weight = 80

[[endpoints]]
name = "server2"
ip = "192.168.1.11"
port = 50051
weight = 10

[[endpoints]]
name = "server3"
ip = "192.168.1.12"
port = 50051
weight = 10