[[endpoints]]
name = "s1"
ip = "192.168.1.1"
port = 8080
weight = 80

[[endpoints]]
name = "s2"
ip = "192.168.1.2"
port = 8081
weight = 10

[[endpoints]]
name = "s3"
ip = "192.168.1.3"
port = 8082
weight = 10